services:
  backend:
    image: ghcr.io/nilshartmann-workshops/jsdays-2026-fullstack-bootcamp/backend:073348b843c6cbcfd37f1805c182a25f7dc1606b
    env_file:
      - ./backend/.env
    environment:
      DB_PATH: /var/lib/backend-db/data.db
    volumes:
      - backend_db:/var/lib/backend-db
    networks:
      - default

  frontend:
    image: ghcr.io/nilshartmann-workshops/jsdays-2026-fullstack-bootcamp/react-spa:073348b843c6cbcfd37f1805c182a25f7dc1606b
    ports:
      - "5200:80"
    depends_on:
      - backend
    networks:
      - default

volumes:
  backend_db:
